### ISSUE TITLE
EXCLUDED_HEADERS are too strict from a Pentester point of view

### ISSUE THREAD

**Issue by cwaazywabbit** [tagomaru/burp-extension-postman-integration#1]
The headers removed include for example:
"Host", "User-Agent", "Origin"

which from a pentester point of view are necessary to remain in the request, as they could be an attack vector.

Cheers

**Comment by tagomaru** [comment]
@cwaazywabbit 
Thx for raising this up.
ok, i will update it, just a moment pls.

**Comment by tagomaru** [comment]
Use https://github.com/tagomaru/burp-extension-postman-integration/blob/v1.1/build/libs/postman-integration-1.1.jar temporally.

This will be published to BApp Store at a later date.

**Comment by cwaazywabbit** [comment]
Thanks for the swift response. We have already cloned a local copy for our custom needs, but thanks for the minor build.
Looking forward to seeing it pushed to BApp store, which would make it easier to track future releases.

Cheers

**Comment by cwaazywabbit** [comment]
v1.2 is now available on BApp Store. I think it's time to close this issue :-)

https://github.com/portswigger/postman-integration
