### ISSUE TITLE
Burp Extension only exports to Postman Collection v1

### ISSUE THREAD

**Issue by x0rb3l** [tagomaru/burp-extension-postman-integration#5]
When using the extension to export a request as a Postman Collection, the format is in v1. The most updated version of Postman only support the v2 format. Will there be any update to support conversion to v2? The current work around is to use the [postman-collection-transformer](https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#converting-postman-collections-from-v1-to-v2) but it would be nice to not have to use the tool every time.

![postman_import](https://user-images.githubusercontent.com/29740744/174459539-880af510-23ad-4478-9b74-8a5fd16694f7.png)

**Comment by else-testet** [comment]
Hey, Im facing the same issue and would be interested in a fix of it :]

**Comment by tagomaru** [comment]
Hi @x0rb3l and @else-testet 

Thank you for being interested in this tool.
Yes, I think it should support v2.

@else-testet 
Do you mean you may fix on your own?

If not, I will fix it.

**Comment by marcioalm** [comment]
That would be great if you could push an update to that @tagomaru .

I'll be watching this issue to get an update when u push the fix.

Best Regards.

**Comment by else-testet** [comment]
@tagomaru 
Thanks for your response!
no, that's not what I meant. I cannot fix it 😅 just awaiting your fix :)
Thank you in advance!

**Comment by tagomaru** [comment]
Okay, I'll work on this.

**Comment by tagomaru** [comment]
I fixed this. I'll let you know once it is released to the market.

**Comment by tagomaru** [comment]
Hi
The version 2.0 generating postman v2 format has been released on the BApp Store.

https://portswigger.net/bappstore/6ae9ede3630949748842a43518e840a7

Thank you for your patient and interest of this extension!
